=== R2D2ar/WebEngineeringLabor/Labor2/Aufgabe1.2/textformat.dtd
<!ELEMENT dokument (ueberschrift, absatz+, leerzeile?)>
        <!ELEMENT ueberschrift (#PCDATA)>
        <!ELEMENT absatz (fett|kursiv|normal)*>
        <!ELEMENT leerzeile EMPTY>

        <!ELEMENT fett (#PCDATA)>
        <!ELEMENT kursiv (#PCDATA)>
        <!ELEMENT normal (#PCDATA)>
        <!ENTITY nbsp "&#160;">

=== R2D2ar/WebEngineeringLabor/Labor2/Aufgabe1.2/document.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dokument SYSTEM "textformat.dtd">
<dokument>
    <ueberschrift>Edward Snowden</ueberschrift>
    <absatz>
        <fett>Edward Snowden</fett> <normal>ist ein</normal>
        <kursiv>US-amerikanischer Whistleblower</kursiv> <normal>und ehemaliger</normal>
        <kursiv>CIA-Mitarbeiter</kursiv><normal>. Seine Enthüllungen
        gaben Einblicke in das Ausmaß der weltweiten Überwachungs- und
        Spionagepraktiken von Geheimdiensten – überwiegend jenen der Vereinigten Staaten und Großbritanniens.
        Diese lösten im Sommer 2013 die NSA-Affäre aus.</normal>
    </absatz>
    <absatz>
        <normal>Er wurde dafür mehrfach von nichtstaatlichen Organisationen ausgezeichnet und
        für den Friedensnobelpreis nominiert.</normal>
    </absatz>
</dokument>
